
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const IS_ALREADY_LOGGED_IN = 'IS_ALREADY_LOGGED_IN';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
